### ISSUE TITLE
Indicate processing state after clicking on "Continue"

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/3id-connect#60]
Spinner maybe.

**Comment by zachferland** [comment]
Added loading feedback/spinner to all ops that take longer than a few ms

**Comment by dabit3** [comment]
I wanted to follow up because I think this is a pretty significant feature that would very much improve user experience, so if it's there and I'm not implementing it properly I'd love to figure out how to show some type of activity indicator.

I've attached the video of a basic testing app I'm working on to give you an idea of what I have now.

From what I can tell, there is no indicator as to any activity that is happening in the background. 

Also, are there suggestions on how to improve the user feedback I may want to offer during the authentication flow that may be handled on the client?

Thanks!

https://user-images.githubusercontent.com/1857282/121611042-fdbf4d80-ca1c-11eb-8319-5dd524bf0b17.mp4

**Comment by oed** [comment]
That's odd. There is usually a spinner on the "continue" button!

**Comment by dabit3** [comment]
Hi @oed , are there any suggestions to why this may not be working as expected?

I'd also be happy to dive into the code and possibly submit a PR if you don't think this is something like a degradation or an easy fix.

Thanks for your time on this!

**Comment by zachferland** [comment]
Added issue here 
https://github.com/ceramicstudio/3id-connect/issues/88
